# Generated by Django 5.0.3 on 2024-05-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_goal_completed_at_goal_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='intensity',
        ),
        migrations.AddField(
            model_name='workout',
            name='activity_type',
            field=models.CharField(choices=[('run', 'Run'), ('walk', 'Walk'), ('bike', 'Bike'), ('swim', 'Swim'), ('hike', 'Hike'), ('dance', 'Dance')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='calories_burned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='distance_miles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='weight_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='weight_type',
            field=models.CharField(blank=True, choices=[('barbell', 'Barbell'), ('body_weight', 'Body Weight'), ('kettlebells', 'Kettlebells'), ('dumbbells', 'Dumbbells')], max_length=20, null=True),
        ),
    ]
