# Generated by Django 5.0.3 on 2024-05-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_workout_intensity_workout_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='distance_unit',
            field=models.CharField(blank=True, choices=[('km', 'Kilometers'), ('mi', 'Miles')], default='km', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], default='lbs', max_length=3),
        ),
    ]
