# Generated by Django 5.0.3 on 2024-05-10 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_workout_distance_unit_workout_weight_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterintake',
            name='amount_oz',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='waterintake',
            name='amount_ml',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='waterintake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_intake', to='tracker.user'),
        ),
    ]
